project:
  type: website
  output-dir: docs

website:
  title: "Shuhei's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # プロジェクトページを別途作るまでは、HomeだけでOKです
      # - href: projects.qmd
      #   text: Projects
      # cv.pdf を置いたら以下の#を外してください
      # - href: cv.pdf
      #   text: CV
    right:
      - icon: github
        href: https://github.com/Shuhei113
      - icon: linkedin
        href: https://www.linkedin.com/in/Shuhei113

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
